### ISSUE TITLE
Question: Does Forecat benefit from my translation memory?

### ISSUE THREAD

**Issue by MoamenAbdelsattar** [dtr5/Forecat-OmegaT#11]
I'm looking for an offline machine translation that can benefit from my translation memory to concentrate on the subject I'm translating, does Forecat use the translation memory or is it only using the data it has trained on firstly?

**Comment by kosivantsov** [comment]
Forecat plugin by itself does neither. In the essence, it cuts your current segment into subsegments and sends them to OmegaT-supported MT engines enabled in the plugin. Then it builds a set of autocompletion suggestions. Depending on the language you translate into, those subsegment suggestions might be very helpful.

Having said that, GitHub repository issues section doesn't seem like the best place to ask about [documented behavior](https://github.com/transducens/forecat/blob/master/README.md).

**Comment by MoamenAbdelsattar** [comment]
Thank you!

**Comment by eltorre** [comment]
Hi @MoamenAbdelsattar,

as Kos pointed out, forecat does not offer machine translation capabilities, it just uses MT as provided by other OmegaT plugins.

I am not sure how to directly use a translation memory with this approach, as likely you will have full segments on it, and no way to directly extract translations for the subsegements.

Some options for offline MT:
* https://github.com/transducens/apertium-cli-omegat if your language pair is supported by Apertium
* as an alternative, run Apertium-apy (HTTP server frontend to Apertium) https://github.com/apertium/apertium-python and use the out of the box Apertium plugin, pointing it to your local URL
* the apertium-cli-omegat codebase can be used as a template to use any other local MT you have that runs *NIX-like, that is, pipe segments in stdin, translations come out stdout

Please note that the whole idea of forecat is heavily inspired on phrase-based machine translation:
* the phrase table is the MT models and bilingual resources used to translate the subsegments
* the decoder is the user typing the output and optionally accepting suggestions

The suggestions are ranked using a simple heuristic, or a neural network model you can train on your data.

I would expect neural machine translation to produce subpar suggestions when it comes to this usage. Instead you can use neural interactive translation prediction, where basically you fix the prefix of the NMT output to whatever you have typed, and you get as a suggestion the rest of the segment. But I do not know of any reference implementation for this, and this functionality is not part of forecat.

As a side note I just tested Forecat-OmegaT against Omegat 5.7.1 and it seems to work fine apart of having a non-standard configuration menu.
